spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/todomeet?serverTimezone=Asia/Seoul
    username: root
    password: 12345678
  jpa:
    database: mysql
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        default_batch_fetch_size: 1000

  # application.yml
  security:
    enable-csrf: false
#  cloud:
#    gcp:
#      storage:
#        credentials:
#          location: classpath:applied-card-403302-4a5091591256.json
#        project-id: applied-card-403302
#        bucket: matna-bucket

server:
  port: 8080
error:
  include-stacktrace=never
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.springframework: DEBUG





#?? - ??? ??
decorator:
  datasource:
    p6spy:
      enable-logging: true
      multiline: true
      logging: slf4j

#JWT

app:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    accessTokenExpiration:
      milliseconds: 3600000  # 1시간
    refreshTokenExpiration:
      milliseconds: 604800000  # 1주일
